package com.manashiki.uchilearte.logica.dao;

import java.util.List;

import com.manashiki.uchilearte.logica.entidad.AsignaturaTomadaProgramaActivoSemestreEntity;
import com.manashiki.uchilearte.logica.exception.PersistenceImplException;

public interface AsignaturaTomadaProgramaActivoSemestreDAO{
	
	public AsignaturaTomadaProgramaActivoSemestreEntity crearAsignaturaTomadaProgramaActivoSemestreEntity(AsignaturaTomadaProgramaActivoSemestreEntity objAsignaturaTomadaProgramaActivoSemestreEntity );
	public AsignaturaTomadaProgramaActivoSemestreEntity actualizarAsignaturaTomadaProgramaActivoSemestreEntity(AsignaturaTomadaProgramaActivoSemestreEntity objAsignaturaTomadaProgramaActivoSemestreEntity );
 	public AsignaturaTomadaProgramaActivoSemestreEntity buscarAsignaturaTomadaProgramaActivoSemestrexIdEntity(AsignaturaTomadaProgramaActivoSemestreEntity objAsignaturaTomadaProgramaActivoSemestreEntity ) throws PersistenceImplException;
 	public List<AsignaturaTomadaProgramaActivoSemestreEntity> listarAsignaturaTomadaProgramaActivoSemestreEntity();
}
