package com.manashiki.uchilearte.logica.dao;

import java.util.List;

import com.manashiki.uchilearte.logica.entidad.SolicitudCertificadoEntity;
import com.manashiki.uchilearte.logica.exception.PersistenceImplException;


public interface SolicitudCertificadoDAO{
	
	public SolicitudCertificadoEntity crearSolicitudCertificadoEntity(SolicitudCertificadoEntity objSolicitudCertificadoEntity);
	public SolicitudCertificadoEntity actualizarSolicitudCertificadoEntity(SolicitudCertificadoEntity objSolicitudCertificadoEntity);
	public SolicitudCertificadoEntity buscarSolicitudCertificadoxIdEntity(SolicitudCertificadoEntity objSolicitudCertificadoEntity) throws PersistenceImplException;
	public SolicitudCertificadoEntity buscarSolicitudCertificadoxRutPersonaSolicitudCertificadoEntity(SolicitudCertificadoEntity objSolicitudCertificadoEntity) throws PersistenceImplException;
	public SolicitudCertificadoEntity buscarSolicitudCertificadoxNombrePersonaSolicitudCertificadoEntity(SolicitudCertificadoEntity objSolicitudCertificadoEntity) throws PersistenceImplException;
	
	public List<SolicitudCertificadoEntity> listarSolicitudCertificadosEntity();
	public List<SolicitudCertificadoEntity> listarSolicitudCertificadoxApellidoPaternoPersonaSolicitudCertificadoEntity(SolicitudCertificadoEntity objSolicitudCertificadoEntity);
	public List<SolicitudCertificadoEntity> listarSolicitudCertificadoxEntreFechasEntity(SolicitudCertificadoEntity objSolicitudCertificadoInicial, SolicitudCertificadoEntity objSolicitudCertificadoFinal);
	public List<SolicitudCertificadoEntity> listarSolicitudCertificadoxEstadoEntity(SolicitudCertificadoEntity objSolicitudCertificadoEntity);
	
}