package com.manashiki.uchilearte.logica.dao;

import java.util.List;

import com.manashiki.uchilearte.logica.entidad.SolicitudPostulacionEntity;
import com.manashiki.uchilearte.logica.exception.PersistenceImplException;


public interface SolicitudPostulacionDAO{
	
	public SolicitudPostulacionEntity crearSolicitudPostulacionEntity(SolicitudPostulacionEntity solicitudPostulacionEntity);
	public SolicitudPostulacionEntity actualizarSolicitudPostulacionEntity(SolicitudPostulacionEntity solicitudPostulacionEntity);
	public SolicitudPostulacionEntity buscarSolicitudPostulacionxIdEntity(SolicitudPostulacionEntity solicitudPostulacionEntity) throws PersistenceImplException;
	public SolicitudPostulacionEntity buscarSolicitudPostulacionxRutPersonaSolicitudPostulacionEntity(SolicitudPostulacionEntity solicitudPostulacionEntity) throws PersistenceImplException;
	public SolicitudPostulacionEntity buscarSolicitudPostulacionxNombrePersonaSolicitudPostulacionEntity(SolicitudPostulacionEntity solicitudPostulacionEntity) throws PersistenceImplException;
	
	public List<SolicitudPostulacionEntity> listarSolicitudPostulacionesEntity();
	public List<SolicitudPostulacionEntity> listarSolicitudPostulacionxApellidoPaternoPersonaSolicitudPostulacionEntity(SolicitudPostulacionEntity solicitudPostulacionEntity);
	public List<SolicitudPostulacionEntity> listarSolicitudPostulacionxEntreFechasEntity(SolicitudPostulacionEntity solicitudPostulacionInicial, SolicitudPostulacionEntity solicitudPostulacionFinal);
	public List<SolicitudPostulacionEntity> listarSolicitudPostulacionxEstadoEntity(SolicitudPostulacionEntity solicitudPostulacionEntity);
	
}