package com.manashiki.uchilearte.negocio.dao;

import java.util.List;

import com.manashiki.uchilearte.negocio.exception.NegocioImplException;
import com.manashiki.uchilearte.negocio.model.AsignaturaTomadaProgramaActivoSemestreModel;


public interface AsignaturaTomadaProgramaActivoSemestreNegocioDAO{
	
	public AsignaturaTomadaProgramaActivoSemestreModel crearAsignaturaTomadaProgramaActivoSemestreModel(AsignaturaTomadaProgramaActivoSemestreModel objAsignaturaTomadaProgramaActivoSemestreModel );
	public AsignaturaTomadaProgramaActivoSemestreModel actualizarAsignaturaTomadaProgramaActivoSemestreModel(AsignaturaTomadaProgramaActivoSemestreModel objAsignaturaTomadaProgramaActivoSemestreModel );
 	public AsignaturaTomadaProgramaActivoSemestreModel buscarAsignaturaTomadaProgramaActivoSemestrexIdModel(AsignaturaTomadaProgramaActivoSemestreModel objAsignaturaTomadaProgramaActivoSemestreModel ) throws NegocioImplException;
 	public List<AsignaturaTomadaProgramaActivoSemestreModel> listarAsignaturaTomadaProgramaActivoSemestreModel();
}
