package com.manashiki.uchilearte.negocio.dao;

import java.util.List;

import com.manashiki.uchilearte.negocio.exception.NegocioImplException;
import com.manashiki.uchilearte.negocio.model.SolicitudPostulacionModel;

public interface SolicitudPostulacionNegocioDAO{
	
	public SolicitudPostulacionModel crearSolicitudPostulacionModel(SolicitudPostulacionModel objSolicitudPostulacionModel);
	public SolicitudPostulacionModel actualizarSolicitudPostulacionModel(SolicitudPostulacionModel objSolicitudPostulacionModel);
	public SolicitudPostulacionModel buscarSolicitudPostulacionxIdModel(SolicitudPostulacionModel objSolicitudPostulacionModel) throws NegocioImplException;
	public SolicitudPostulacionModel buscarSolicitudPostulacionxRutPersonaSolicitudPostulacionModel(SolicitudPostulacionModel objSolicitudPostulacionModel) throws NegocioImplException;
	public SolicitudPostulacionModel buscarSolicitudPostulacionxNombrePersonaSolicitudPostulacionModel(SolicitudPostulacionModel objSolicitudPostulacionModel) throws NegocioImplException;
	public List<SolicitudPostulacionModel> listarSolicitudPostulacionesModel();
	public List<SolicitudPostulacionModel> listarSolicitudPostulacionxApellidoPaternoPersonaSolicitudPostulacionModel(SolicitudPostulacionModel objSolicitudPostulacionModel);
//	public List<SolicitudPostulacionModel> listarSolicitudPostulacionxTipoSolicitudModel(SolicitudPostulacionModel objSolicitudPostulacionModel);
	public List<SolicitudPostulacionModel> listarSolicitudPostulacionxxEntreFechasModel(SolicitudPostulacionModel solicitudPostulacionModelInicial,SolicitudPostulacionModel solicitudPostulacionModelFinal);
	public List<SolicitudPostulacionModel> listarSolicitudPostulacionxEstadoModel(SolicitudPostulacionModel objSolicitudPostulacionModel);
	
}