package com.manashiki.uchilearte.negocio.dao;

import java.util.List;

import com.manashiki.uchilearte.negocio.exception.NegocioImplException;
import com.manashiki.uchilearte.negocio.model.SolicitudCertificadoModel;


public interface SolicitudCertificadoNegocioDAO{
	
	public SolicitudCertificadoModel crearSolicitudCertificadoModel(SolicitudCertificadoModel objSolicitudCertificadoModel);
	public SolicitudCertificadoModel actualizarSolicitudCertificadoModel(SolicitudCertificadoModel objSolicitudCertificadoModel);
	public SolicitudCertificadoModel buscarSolicitudCertificadoxIdModel(SolicitudCertificadoModel objSolicitudCertificadoModel) throws NegocioImplException;
	public SolicitudCertificadoModel buscarSolicitudCertificadoxRutPersonaSolicitudCertificadoModel(SolicitudCertificadoModel objSolicitudCertificadoModel) throws NegocioImplException;
//	public SolicitudCertificadoModel buscarSolicitudCertificadoxNombrePersonaSolicitudCertificadoModel(SolicitudCertificadoModel objSolicitudCertificadoModel) throws NegocioImplException;
	public List<SolicitudCertificadoModel> listarSolicitudCertificadosModel();
	public List<SolicitudCertificadoModel> listarSolicitudCertificadoxApellidoPaternoPersonaSolicitudCertificadoModel(SolicitudCertificadoModel objSolicitudCertificadoModel);
	public List<SolicitudCertificadoModel> listarSolicitudCertificadoxEntreFechasModel(SolicitudCertificadoModel solicitudCertificadoModelInicial,SolicitudCertificadoModel solicitudCertificadoModelFinal);
	public List<SolicitudCertificadoModel> listarSolicitudCertificadoxEstadoModel(SolicitudCertificadoModel objSolicitudCertificadoModel);

}