package com.manashiki.uchilearte.negocio.dao;

import java.util.List;

import com.manashiki.uchilearte.negocio.exception.NegocioImplException;
import com.manashiki.uchilearte.negocio.model.SolicitudAcademicaModel;

public interface SolicitudAcademicaNegocioDAO{
	
	public SolicitudAcademicaModel crearSolicitudAcademicaModel(SolicitudAcademicaModel objSolicitudAcademicaModel);
	public SolicitudAcademicaModel actualizarSolicitudAcademicaModel(SolicitudAcademicaModel objSolicitudAcademicaModel);
	public SolicitudAcademicaModel buscarSolicitudAcademicaxIdModel(SolicitudAcademicaModel objSolicitudAcademicaModel) throws NegocioImplException;
	public SolicitudAcademicaModel buscarSolicitudAcademicaxRutPersonaSolicitudAcademicaModel(SolicitudAcademicaModel objSolicitudAcademicaModel) throws NegocioImplException;
	public SolicitudAcademicaModel buscarSolicitudAcademicaxNombrePersonaSolicitudAcademicaModel(SolicitudAcademicaModel objSolicitudAcademicaModel) throws NegocioImplException;
	public List<SolicitudAcademicaModel> listarSolicitudAcademicasModel();
	public List<SolicitudAcademicaModel> listarSolicitudAcademicaxApellidoPaternoPersonaSolicitudAcademicaModel(SolicitudAcademicaModel objSolicitudAcademicaModel);
	public List<SolicitudAcademicaModel> listarSolicitudAcademicaxTipoSolicitudModel(SolicitudAcademicaModel objSolicitudAcademicaModel);
	public List<SolicitudAcademicaModel> listarSolicitudAcademicaxxEntreFechasModel(SolicitudAcademicaModel solicitudAcademicaModelInicial,SolicitudAcademicaModel solicitudAcademicaModelFinal);
	public List<SolicitudAcademicaModel> listarSolicitudAcademicaxEstadoModel(SolicitudAcademicaModel objSolicitudAcademicaModel);
	
}