package com.manashiki.uchilearte.servicio;

import java.util.List;

import com.manashiki.uchilearte.servdto.dto.entities.formulario.AsignaturaTomadaProgramaActivoSemestreDTO;
import com.manashiki.uchilearte.servicio.exception.ServicioImplException;

public interface IAsignaturaTomadaProgramaActivoSemestreServicio{
	
	public AsignaturaTomadaProgramaActivoSemestreDTO crearAsignaturaTomadaProgramaActivoSemestreDTO(AsignaturaTomadaProgramaActivoSemestreDTO objAsignaturaTomadaProgramaActivoSemestreDTO );
	public AsignaturaTomadaProgramaActivoSemestreDTO actualizarAsignaturaTomadaProgramaActivoSemestreDTO(AsignaturaTomadaProgramaActivoSemestreDTO objAsignaturaTomadaProgramaActivoSemestreDTO );
 	public AsignaturaTomadaProgramaActivoSemestreDTO buscarAsignaturaTomadaProgramaActivoSemestrexIdDTO(AsignaturaTomadaProgramaActivoSemestreDTO objAsignaturaTomadaProgramaActivoSemestreDTO ) throws ServicioImplException;
 	public List<AsignaturaTomadaProgramaActivoSemestreDTO> listarAsignaturaTomadaProgramaActivoSemestreDTO();
}
